name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]   # change to 18.x or 20.x

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install backend dependencies
      run: npm ci
      working-directory: ./react-project-backend

    - name: Build backend
      run: npm run build --if-present
      working-directory: ./react-project-backend

    - name: Run backend tests
      run: npm test
      working-directory: ./react-project-backend

    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./react-project-frontend

    - name: Build frontend
      run: npm run build --if-present
      working-directory: ./react-project-frontend

    - name: Run frontend tests
      run: npm test
      working-directory: ./react-project-frontend
